/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.uoc.eventreg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Image service. Represents a row in the &quot;EVENTREG_Image&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.uoc.eventreg.model.impl.ImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.uoc.eventreg.model.impl.ImageImpl}.
 * </p>
 *
 * @author Ana Mendoza
 * @see Image
 * @see edu.uoc.eventreg.model.impl.ImageImpl
 * @see edu.uoc.eventreg.model.impl.ImageModelImpl
 * @generated
 */
public interface ImageModel extends BaseModel<Image> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a image model instance should use the {@link Image} interface instead.
	 */

	/**
	 * Returns the primary key of this image.
	 *
	 * @return the primary key of this image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this image.
	 *
	 * @param primaryKey the primary key of this image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the image ID of this image.
	 *
	 * @return the image ID of this image
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this image.
	 *
	 * @param imageId the image ID of this image
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the company ID of this image.
	 *
	 * @return the company ID of this image
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this image.
	 *
	 * @param companyId the company ID of this image
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this image.
	 *
	 * @return the group ID of this image
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this image.
	 *
	 * @param groupId the group ID of this image
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the event ID of this image.
	 *
	 * @return the event ID of this image
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this image.
	 *
	 * @param eventId the event ID of this image
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the dl file entry ID of this image.
	 *
	 * @return the dl file entry ID of this image
	 */
	@AutoEscape
	public String getDlFileEntryId();

	/**
	 * Sets the dl file entry ID of this image.
	 *
	 * @param dlFileEntryId the dl file entry ID of this image
	 */
	public void setDlFileEntryId(String dlFileEntryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(edu.uoc.eventreg.model.Image image);

	@Override
	public int hashCode();

	@Override
	public CacheModel<edu.uoc.eventreg.model.Image> toCacheModel();

	@Override
	public edu.uoc.eventreg.model.Image toEscapedModel();

	@Override
	public edu.uoc.eventreg.model.Image toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}